### PR TITLE
adding new option 'debug'

### PR DESCRIPTION
**Pull request by alexander-naumov**

### CODE REVIEW

**Comment by lcheylus** [comment]
Not very useful IHMO, there are few debug infos in `pkgsearch`.

And please don't use UPPERCASE `DEBUG` variable name (only used for global variables) => rename it `debug`.

Fix and simplify your code in `pkgsearch` to set debug as `False` by default: 
```
parser.add_argument(
        "-d",
        "--debug",
        help="enable debug info",
        action='store_true'
    )

    needle = args.package

    create_cache_dir()
    get_index(args.index)
    create_cache_dir(args.debug)
    get_index(args.debug, args.index)
```

**Comment by alexander-naumov** [comment]
> Not very useful IHMO, there are few debug infos in `pkgsearch`.
> 

Right now. yes, but are you going to continue to develop it?

> And please don't use UPPERCASE `DEBUG` variable name (only used for global variables) => rename it `debug`.
> 

I used uppercase, because it's uppercase right now. See L40 or L29.

> Fix and simplify your code in `pkgsearch` to set debug as `False` by default:
> 

It's false by default. See (new version) L132.

**Comment by lcheylus** [comment]
> Right now. yes, but are you going to continue to develop it?

Yes, I have some ideas for future devs but I don't need some extra debug infos.
 
> I used uppercase, because it's uppercase right now. See L40 or L29.

`DEBUG` is defined UPPERCASE because it's an internal global variable (sort of "C define"). According to [Python PEP-8](https://peps.python.org/pep-0008/), case for variable is always lowercase except for constant.

Please learn the basics of coding-style in Python before submitting a PR.

> It's false by default. See (new version) L132.

Yes, but your code is ugly : don't need to set `DEBUG` to False and to copy value from `args.debug`. Using `action='store_true'` from Python `argparse` set default value to `False`.

**Comment by jhx0** [comment]
Thanks both for your work!
I will review the changes in the coming days. 
Not quite sure yet about the debug flag - I need to test this out.

**Comment by jhx0** [comment]
At this stage we will not use a debug switch.
But still, this made me rethink the approach a little - so thanks for that @alexander-naumov !
Also: Feel free to create a issue regarding wanted/needed features - new ideas are always welcome.

**Pull request closed without merging**
